language: go
services:
  - docker
branches:
  only:
  - travis-ci
before_script:
  - bash scripts/docker-build.sh
script:
  - bash scripts/docker-push.sh
before_install:
  - bash scripts/ssh-build.sh
after_success:
  - set -xe
  - bash scripts/deploy.sh
notifications:
  email: false    # default notification method
  slack:
    rooms: # https://docs.travis-ci.com/user/encryption-keys/
      secure: 2usslzMVqPlp4YAbOLs7GmcG7nx2bHPprUFLQxLAuh243Dke2c37i3ttlu1ujJlMy8SXc6OVmJmFkdWfdY+c30MCvw1qpQ+LGxmhvtRFT2EUp7JAesA3BicepFGVo/FGg469BLuu7r59agJQ+k/h2UWPPJmdjkMc138PYzZkuRMvpxGgDdTDCWS1ePlEabCe7ZDBW8x94sSxGVqp4tPmTA1nvWACCifXv2H9yy6gZK9oCXBEFtUrry70/cpEAsHVfYZ+1izncjOdJqJ0AQEPxU71xG8N7M8FrfUFaZhSLuT+uEuB29I8jTfa5zBZC18mN6TTiOxR8F8PgdjfiR+zGaJ80ApdO/LBGskcYEsjZketVtHzOfWoG9W67LUCqdh4POcwHXBpq6TesYXyxqQmQCT76w6CRlfu7ew6bUxQiU145VgHad9dP936cdT2tE1YG8aAycxYP/g+vvLEuQyzILZPnQNdmjZ6mKUmFdoXRhEpBWXSddOq5bVIbUDMnZDiryuLc1enWICoL+y8Bp7bOp4Od7rW6dFiA6sc6MIsm1tJ9kQetFRuW2P2CGqTd/tZu0dLxGPThzLzbjnvOy2hR5ClncLNFRcMyU16qHakuguYr95GoUOOWqUG+yQ2CEEnxigpaZ13Sb6iABCPDekV1qKhXal99wypSb2RCF7eHAk=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
