# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

services:

  app:
    container_name: io-golang
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
